// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjrcilvkhpyyvusuriru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcmNpbHZraHB5eXZ1c3VyaXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTgyMDMsImV4cCI6MjA1ODg5NDIwM30.TCSqFRQXaC_5N9XKp7HCudJifTYsHl5o_OkJ7nHDMj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);